#!/bin/bash

I=`dpkg -l | grep "unzip"`
if [ -n "$I" ]
then
   echo unzip installed
else
   sudo apt-get install unzip -y
fi

start() {
  local fullname="$1"
  local filename=`basename "$1"`
  local fileext="${filename##*.}"
  if  [[ $fileext = "zip" ]]
    then
	unzip "$fullname" -d "${fullname%/*}"
	rm "$fullname"
  fi
}

scan() {
  local x;
  for e in "$1"/*; do
    x=${e##*/}
    if [ -d "$e" -a ! -L "$e" ]
    then
      scan "$e"
    else
      start "$e"
    fi
  done
}

[ $# -eq 0 ] && dir=`pwd` || dir=$@


scan "$dir"
